### ISSUE TITLE
Project Config

### ISSUE THREAD

**Issue by gin0115** [gin0115/wp-scoper-core#3]
- [ ] https://github.com/gin0115/wp-scoper-core/issues/4
- [x] https://github.com/gin0115/wp-scoper-core/issues/5
- [ ] https://github.com/gin0115/wp-scoper-core/issues/6

## Todo in later phase
- [ ] Include edit config
